server:
  host: 0.0.0.0
  port: 57002
  contextPath: /governance

eyesmedia:
  locale: zh_TW
  localTimeZone: Asia/Taipei
  api:
    path-name: api
    version: v1
  database:
    mysql-dc-governance:
      host: newsdb.c1u1qhoyb2gi.ap-northeast-1.rds.amazonaws.com
      port: 3306
      dbname: sit_dc_governance
      username: dc-user
      password: 28010606
      charset: utf8mb4
