version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s [%(threadName)s-%(process)d] %(levelname)-5s %(module)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
#    class: logging.handlers.RotatingFileHandler
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
#    maxBytes: 10485760 # 10MB
#    backupCount: 20
    encoding: utf-8
    when: 'D'

  error_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/errors.log
    encoding: utf-8
    when: 'D'
#    interval: 1
#    backupCount: 1

loggers:
  '':
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
  application:
    level: INFO
    handlers: [console, info_file_handler]
    propagate: no
  eyesmediapydb:
    level: ERROR
    handlers: [console, info_file_handler]
    propagate: no
  boto3:
    level: INFO
    handlers: [console, info_file_handler]
    propagate: no
  mongo:
    level: ERROR
    handlers: [console, error_file_handler]
    propagate: no
  elasticsearch:
    level: ERROR
    handlers: [console, error_file_handler]
    propagate: no
  mysql:
    level: ERROR
    handlers: [console, error_file_handler]
    propagate: no
  gunicorn:
    level: INFO
    handlers: [console, info_file_handler]
    propagate: no
  gunicorn.error:
    level: INFO
    handlers: [console, error_file_handler]
    propagate: no
  gunicorn.access:
    level: INFO
    handlers: [console, info_file_handler]
    propagate: no
